const fs = require('fs');
const path = require('path');

const translations = {
  "de.json": {
    "Overview": "Übersicht",
    "Growth Analysis": "Wachstumsanalyse",
    "Kingdom Analysis": "Königreich Analyse",
    "Alliance Duel": "Allianzduell",
    "Scatter Plot": "Streudiagramm",
    "Hall of Legends": "Halle der Legenden",
    "Team Builder": "Teambuilder",
    "Alliance Merge": "Allianzzusammenführung",
    "Fixed MGE": "Festes MGE",
    "Roster Linker": "Kader-Verknüpfung",
    "Configuration": "Konfiguration",
    "Results": "Ergebnisse",
    "workbench_title": "Königreich-Werkbank",
    "workbench_subtitle": "Interaktive Legacy-Tools",
    "tab_in_dev": "Tab In Entwicklung",
    "tab_in_dev_desc": "Die Komponente wird derzeit auf das V2-Framework migriert.",
    "r4_clearance": "R4 Freigabe erforderlich",
    "r4_desc": "Deine Rolle hat keine Berechtigung, dieses Werkzeug anzuzeigen.",
    "Presence Radar": "Präsenzradar",
    "War Room": "Kriegsraum",
    "Roster View": "Kaderansicht"
  },
  "es.json": {
    "Overview": "Visión general",
    "Growth Analysis": "Análisis de Crecimiento",
    "Kingdom Analysis": "Análisis de Reino",
    "Alliance Duel": "Duelo de Alianzas",
    "Scatter Plot": "Gráfico de Dispersión",
    "Hall of Legends": "Salón de Leyendas",
    "Team Builder": "Creador de Equipos",
    "Alliance Merge": "Fusión de Alianzas",
    "Fixed MGE": "MGE Fijo",
    "Roster Linker": "Enlace de Lista",
    "Configuration": "Configuración",
    "Results": "Resultados",
    "workbench_title": "Mesa de Trabajo del Reino",
    "workbench_subtitle": "Herramientas Interactivas",
    "tab_in_dev": "Pestaña En Desarrollo",
    "tab_in_dev_desc": "El componente se encuentra actualmente migrando a V2.",
    "r4_clearance": "Autorización R4 Requerida",
    "r4_desc": "Su rol actual no tiene permiso.",
    "Presence Radar": "Radar de Presencia",
    "War Room": "Sala de Guerra",
    "Roster View": "Vista de Lista"
  },
  "fr.json": {
    "Overview": "Aperçu",
    "Growth Analysis": "Analyse de Croissance",
    "Kingdom Analysis": "Analyse de Royaume",
    "Alliance Duel": "Duel d'Alliance",
    "Scatter Plot": "Nuage de Points",
    "Hall of Legends": "Salle des Légendes",
    "Team Builder": "Créateur d'Équipe",
    "Alliance Merge": "Fusion d'Alliance",
    "Fixed MGE": "MGE Fixe",
    "Roster Linker": "Lieur d'Effectif",
    "Configuration": "Configuration",
    "Results": "Résultats",
    "workbench_title": "Établi du Royaume",
    "workbench_subtitle": "Outils Interactifs",
    "tab_in_dev": "Onglet En Développement",
    "tab_in_dev_desc": "Composant en cours de migration.",
    "r4_clearance": "Autorisation R4 Requise",
    "r4_desc": "Vous n'avez pas l'autorisation.",
    "Presence Radar": "Radar de Présence",
    "War Room": "Salle de Guerre",
    "Roster View": "Vue de l'Effectif"
  },
  "id.json": {
    "Overview": "Ringkasan",
    "Growth Analysis": "Analisis Pertumbuhan",
    "Kingdom Analysis": "Analisis Kerajaan",
    "Alliance Duel": "Duel Aliansi",
    "Scatter Plot": "Plot Sebar",
    "Hall of Legends": "Aula Legenda",
    "Team Builder": "Pembuat Tim",
    "Alliance Merge": "Penggabungan Aliansi",
    "Fixed MGE": "MGE Tetap",
    "Roster Linker": "Penaut Daftar",
    "Configuration": "Konfigurasi",
    "Results": "Hasil",
    "workbench_title": "Meja Kerja Kerajaan",
    "workbench_subtitle": "Alat Warisan Interaktif",
    "tab_in_dev": "Aplikasi Dalam Pengembangan",
    "tab_in_dev_desc": "Sedang dalam migrasi V2.",
    "r4_clearance": "Diperlukan Izin R4",
    "r4_desc": "Peran Anda tidak diizinkan.",
    "Presence Radar": "Radar Kehadiran",
    "War Room": "Ruang Perang",
    "Roster View": "Tampilan Daftar"
  },
  "ko.json": {
    "Overview": "개요",
    "Growth Analysis": "성장 분석",
    "Kingdom Analysis": "왕국 분석",
    "Alliance Duel": "연맹 대결",
    "Scatter Plot": "산점도",
    "Hall of Legends": "명예의 전당",
    "Team Builder": "팀 빌더",
    "Alliance Merge": "연맹 합병",
    "Fixed MGE": "고정 MGE",
    "Roster Linker": "명단 링커",
    "Configuration": "구성",
    "Results": "결과",
    "workbench_title": "왕국 작업대",
    "workbench_subtitle": "대화형 도구",
    "tab_in_dev": "개발 중인 탭",
    "tab_in_dev_desc": "이 구성 요소는 현재 V2 프레임워크로 마이그레이션 중입니다.",
    "r4_clearance": "R4 권한 필요",
    "r4_desc": "이 유틸리티를 볼 수 있는 권한이 없습니다.",
    "Presence Radar": "존재 레이더",
    "War Room": "작전 회의실",
    "Roster View": "명단 보기"
  },
  "pt.json": {
    "Overview": "Visão Geral",
    "Growth Analysis": "Análise de Crescimento",
    "Kingdom Analysis": "Análise do Reino",
    "Alliance Duel": "Duelo de Alianças",
    "Scatter Plot": "Gráfico de Dispersão",
    "Hall of Legends": "Salão das Lendas",
    "Team Builder": "Construtor de Equipes",
    "Alliance Merge": "Fuso de Alianças",
    "Fixed MGE": "MGE Fixo",
    "Roster Linker": "Vinculador de Roster",
    "Configuration": "Configuração",
    "Results": "Resultados",
    "workbench_title": "Bancada do Reino",
    "workbench_subtitle": "Ferramentas Interativas",
    "tab_in_dev": "Aba em Desenvolvimento",
    "tab_in_dev_desc": "Em migração para V2.",
    "r4_clearance": "Autorização R4 Necessária",
    "r4_desc": "Você não tem permissão.",
    "Presence Radar": "Radar de Presença",
    "War Room": "Sala de Guerra",
    "Roster View": "Ver Lista"
  },
  "ru.json": {
    "Overview": "Обзор",
    "Growth Analysis": "Анализ роста",
    "Kingdom Analysis": "Анализ королевства",
    "Alliance Duel": "Дуэль альянсов",
    "Scatter Plot": "Диаграмма рассеяния",
    "Hall of Legends": "Зал Легенд",
    "Team Builder": "Конструктор команд",
    "Alliance Merge": "Слияние альянсов",
    "Fixed MGE": "Фиксированный MGE",
    "Roster Linker": "Связь списков",
    "Configuration": "Конфигурация",
    "Results": "Результаты",
    "workbench_title": "Панель Королевства",
    "workbench_subtitle": "Интерактивные инструменты",
    "tab_in_dev": "В разработке",
    "tab_in_dev_desc": "В состоянии миграции на V2.",
    "r4_clearance": "Требуется доступ R4",
    "r4_desc": "У вас нет прав.",
    "Presence Radar": "Радар присутствия",
    "War Room": "Военная комната",
    "Roster View": "Просмотр списка"
  },
  "tr.json": {
    "Overview": "Genel Bakış",
    "Growth Analysis": "Büyüme Analizi",
    "Kingdom Analysis": "Krallık Analizi",
    "Alliance Duel": "İttifak Düellosu",
    "Scatter Plot": "Dağılım Grafiği",
    "Hall of Legends": "Efsaneler Salonu",
    "Team Builder": "Takım Kurucu",
    "Alliance Merge": "İttifak Birleşimi",
    "Fixed MGE": "Sabit MGE",
    "Roster Linker": "Kadro Bağlayıcı",
    "Configuration": "Yapılandırma",
    "Results": "Sonuçlar",
    "workbench_title": "Krallık Çalışma Masası",
    "workbench_subtitle": "Etkileşimli Araçlar",
    "tab_in_dev": "Geliştirme Aşamasında",
    "tab_in_dev_desc": "V2 geçişi sürecinde.",
    "r4_clearance": "R4 Yetkisi Gereklidir",
    "r4_desc": "Bunu görüntüleme yetkiniz yok.",
    "Presence Radar": "Durum Radarı",
    "War Room": "Savaş Odası",
    "Roster View": "Kadro Görünümü"
  },
  "vi.json": {
    "Overview": "Tổng quan",
    "Growth Analysis": "Phân tích tăng trưởng",
    "Kingdom Analysis": "Phân tích vương quốc",
    "Alliance Duel": "Đấu trường Liên minh",
    "Scatter Plot": "Bản đồ phân tán",
    "Hall of Legends": "Sảnh Huyền thoại",
    "Team Builder": "Trình tạo đội",
    "Alliance Merge": "Sát nhập Liên minh",
    "Fixed MGE": "MGE Cố định",
    "Roster Linker": "Trình liên kết danh sách",
    "Configuration": "Cấu hình",
    "Results": "Kết quả",
    "workbench_title": "Bàn làm việc Vương quốc",
    "workbench_subtitle": "Công cụ Tương tác",
    "tab_in_dev": "Tab đang phát triển",
    "tab_in_dev_desc": "Đang chuyển đổi sang V2.",
    "r4_clearance": "Yêu cầu quyền R4",
    "r4_desc": "Bạn không có quyền.",
    "Presence Radar": "Radar hiện diện",
    "War Room": "Phòng Chiến tranh",
    "Roster View": "Xem danh sách"
  },
  "zh.json": {
    "Overview": "概况",
    "Growth Analysis": "成长分析",
    "Kingdom Analysis": "王国分析",
    "Alliance Duel": "联盟对决",
    "Scatter Plot": "散点图",
    "Hall of Legends": "传奇殿堂",
    "Team Builder": "团队建设",
    "Alliance Merge": "联盟合并",
    "Fixed MGE": "固定MGE",
    "Roster Linker": "名单链接器",
    "Configuration": "配置",
    "Results": "结果",
    "workbench_title": "王国工作台",
    "workbench_subtitle": "交互式工具",
    "tab_in_dev": "开发中",
    "tab_in_dev_desc": "当前组件正在迁移到V2。",
    "r4_clearance": "需要R4权限",
    "r4_desc": "您没有权限查看。",
    "Presence Radar": "状态雷达",
    "War Room": "作战室",
    "Roster View": "成员名单"
  }
};

const dir = 'e:/UnityBU/unity-v2/src/messages';
for(const [file, trans] of Object.entries(translations)) {
  const fp = path.join(dir, file);
  if(fs.existsSync(fp)) {
     const data = JSON.parse(fs.readFileSync(fp, 'utf8'));
     data.Tabs = { ...data.Tabs, ...trans };
     fs.writeFileSync(fp, JSON.stringify(data, null, 4));
     console.log('Updated ' + file);
  }
}
