const fs = require('fs');
const path = require('path');

const locales = ['en', 'es', 'fr', 'ar', 'zh', 'vi', 'ko', 'ru', 'tr', 'de', 'pt', 'id'];

const data = {
    "en": {
        "DKP": {
            "title": "DKP Results",
            "subtitle": "Dragon Kill Points (Post-KvK Aggregation)",
            "no_lethality": "No Lethality Identified",
            "no_lethality_desc": "Cannot calculate algorithmic models. Double check chronological mapping logic over the latest server timeline.",
            "top_vanguard": "Undisputed Kingdom Vanguard",
            "tier_output": "Tier {tier} Output",
            "calculated_dkp": "Calculated DKP Contribution",
            "official_commendations": "Official KvK Commendations",
            "nodes_indexed": "{count} Nodes Indexed",
            "col_rank": "Rank",
            "col_grade": "Performance Grade",
            "col_name": "Governor Name",
            "col_dkp": "DKP Total",
            "col_deads": "Core Drops (Deads)",
            "col_kp": "Kill Point Deltas",
            "dkp_suffix": "(+{val} DKP)"
        },
        "Upload": {
            "title": "Data Ingestion Hub",
            "subtitle": "Select an ingestion pipeline to synchronize external Kingdom intelligence with the secure AWS Unity Cloud",
            "raw_spreadsheets": "Raw Spreadsheets",
            "raw_desc": "Upload massive Excel or CSV bulk scans generated by RokBoard or other OCR extractors to process thousands of governor records.",
            "cloud_db": "Cloud Database",
            "cloud_desc": "Establish a direct, encrypted uplink to the centralized AWS datastore to synchronize Cross-Kingdom timelines instantly.",
            "ai_scanner": "AI Vision Scanner",
            "ai_desc": "Extract player stat profiles instantly using edge instances of the Gemini Vision AI model.",
            "in_dev": "IN DEVELOPMENT"
        },
        "PreKVK": {
            "title": "PRE-KVK RANKINGS",
            "subtitle": "GLOBAL TOP 300 COMPARISON",
            "target_scope": "TARGET SCOPE:",
            "global_scope": "Global Scope (All Servers)",
            "enter_kd": "Enter KD # (e.g. 3065)",
            "target_count": "TARGET SCOPE: {count} KINGDOMS",
            "col_rank": "RANK",
            "col_kingdom": "KINGDOM",
            "col_power": "TOP 300 POWER",
            "col_kp": "TOTAL KP",
            "col_prank": "POWER RANK",
            "col_kprank": "KP RANK"
        },
        "GlobalAnalysis": {
            "title": "GLOBAL ANALYSIS",
            "subtitle": "CROSS-SERVER MACRO DIAGNOSTICS",
            "camp_builder": "CAMP BUILDER",
            "delta_analytics": "DELTA ANALYTICS",
            "all_kd_analysis": "ALL KINGDOM ANALYSIS",
            "comprehensive_deltas": "COMPREHENSIVE POWER & KP DELTAS ACROSS SELECTED SCANS",
            "filter_kd": "FILTER KD (OPTIONAL)",
            "add": "Add",
            "start_scan": "START SCAN:",
            "end_scan": "END SCAN:",
            "col_kd": "KINGDOM",
            "col_start_p": "TOTAL START POWER",
            "col_end_p": "TOTAL END POWER",
            "col_power_d": "POWER \u0394",
            "col_kp_gained": "KP GAINED",
            "col_deads": "DEAD TROOPS",
            "insufficient": "INSUFFICIENT SCANS TO CALCULATE TEMPORAL DELTAS"
        },
        "Vault": {
            "title": "KINGDOM VAULT",
            "subtitle": "PRE-KVK ECONOMIC RESERVES MATRIX",
            "kingdom_view": "KINGDOM VIEW",
            "sync_aws": "SYNC AWS",
            "override": "SECRET ASSET VERIFICATION OVERRIDE",
            "main_acc": "MAIN ACCOUNT",
            "drag_drop": "DRAG & DROP DATABASE SCREENSHOT",
            "drag_desc": "Our Google Gemini AI Engine will securely read your Food, Wood, Stone, and Gold inventory tokens instantly without logging IP endpoints.",
            "locate_file": "LOCATE FILE"
        },
        "Settings": {
            "title": "Settings",
            "subtitle": "Personal Control Center",
            "section_account": "Account",
            "not_signed_in": "Not Signed In",
            "discord_id": "Discord ID: {id}",
            "auth_desc": "Authenticate via Discord to enable syncing",
            "high_command": "High Command",
            "section_notifications": "Notifications",
            "discord_pings": "Discord Pings",
            "discord_pings_desc": "Receive direct messages from Unity Bot for scan completions",
            "email_notifs": "Email Notifications",
            "email_notifs_desc": "Weekly digest reports and security alerts",
            "section_dashboard": "Dashboard Experience",
            "show_alliance_tag": "Show Alliance Tags",
            "show_alliance_tag_desc": "Display bracket tags before governor names globally",
            "default_kingdom": "Default Kingdom",
            "default_kingdom_desc": "Your primary dashboard routing parameter",
            "no_arch_keys": "No Architectural Keys Verified.",
            "section_api": "External API Connections",
            "hybrid_mode": "Hybrid Mode",
            "api_desc": "Unity runs a hybrid cloud infrastructure. Heavy OCR analysis for image uploads requires a Google Gemini Pro API key to operate.",
            "gemini_key": "Google Gemini Secret Key"
        },
        "Changelog": {
            "title": "Changelog",
            "subtitle": "System Updates & Version History",
            "label_major": "MAJOR",
            "releases": {
                "2_2_1": {
                    "label": "Global Analytics Patches & Feature Expansion",
                    "date": "Late March 2026",
                    "h1": "Secured data integrity globally by permanently fixing Activity Tracker KP drops and missing Dead Troop summaries",
                    "h2": "Overhauled the Discord Server commands route handling to properly mount the /bind Farm Siphoning mechanics",
                    "c1": "Global Analytics (Delta Engine) — Repaired structural mapping bug where calculating dead troop deltas strictly resolved to zero.",
                    "c2": "Activity Tracker Data Normalization — Resolved a case-sensitivity parsing drop from AWS DynamoDB to properly extract kill points.",
                    "c3": "Discord Bot Data Retrieval — Corrected an outdated timestamp mapping pattern that inadvertently blocked /jarvis and /stats API queries.",
                    "c4": "Activity Tracker Wildcards — Upgraded the tracker's dashboard API to permit unbounded cross-kingdom trajectory retrieval.",
                    "c5": "AWS DynamoDB Retroactive Injection — Executed a master system patch to backfill historically missing 'Deads' metrics directly into the chronological data pools.",
                    "c6": "Discord Slash Commands — Overhauled the native Discord /help UI embed and fully mounted the Farm Authentication bindings logic."
                },
                "2_2_0": {
                    "label": "Advanced Data Sandbox & Cloud Forensics",
                    "date": "Late March 2026",
                    "h1": "Engineered a robust Data Sandbox for real-time dynamic mapping of legacy Excel files to native JSON parameters",
                    "h2": "Built end-to-end data audit tracking, permanently linking uploaded Source Files directly into the AWS DynamoDB Global Matrix",
                    "c1": "Sandbox Raw Data Inspector — Admins can dynamically map unrecognizable legacy Excel headers into strict Unity variable structures",
                    "c2": "Explicit DTG Master Control — HTML5 Datetime-local inputs integrated to manually inject exact historical Scan Date times",
                    "c3": "Global Cloud Audit Log Expansion — A new Source Origin column natively tracks and renders the actual Excel file names used to trigger Cloud uploads",
                    "c4": "Origin File Signatures — All Sandbox cloud ingestions are permanently branded with their forensic Filename directly inside the DynamoDB DATES partition key",
                    "c5": "Excel Target Interception — The Sandbox matrix bypasses generic Sheet Names to extract root Kingdom IDs directly from the OS Filename"
                },
                "2_1_0": {
                    "label": "Event & Presence Matrix",
                    "date": "Late March 2026",
                    "h1": "Deployed the Global Event Trajectory AWS engine, securely bridging Web UI and Discord cron jobs",
                    "h2": "Built the Governor Presence tracking architecture for live status webhook routing",
                    "c1": "Global Event Trajectory UI — Web Admins can now map out Competitive schedules natively",
                    "c2": "Governor Presence Modal — Players can sync Working/Sleeping/Vacation schedules directly to AWS",
                    "c3": "Discord Webhook Router — Event cron jobs aggressively ping target channels precisely 15m and 0m before events",
                    "c4": "/event schedule (Discord) — Implemented native Timezone Offset logic to eliminate UTC paradoxes",
                    "c5": "/config channel (Discord) — Administrators can designate exact channels for Pipeline routing",
                    "c6": "Repaired the /bind Discord module and flushed the missing Slash Command arrays into production"
                },
                "2_0_0": {
                    "label": "The V2 Platform Rewrite",
                    "date": "March 2026",
                    "h1": "Full platform rebuild on Next.js + AWS DynamoDB — zero legacy dependencies",
                    "h2": "Discord OAuth authentication replacing manual token flows",
                    "h3": "All pages now server-side rendered with isolated API routes (no exposed secrets)",
                    "h4": "Recharts data visualizations across Kingdom, Global, Pre-KvK and DKP dashboards",
                    "c1": "Kingdom Vault — Leader-only RSS economic reserve tracker",
                    "c2": "Pre-KvK Rankings — Algorithmic Preparedness Score leaderboard with podium",
                    "c3": "DKP Results Board — Post-KvK Tier grading system (S+ through F)",
                    "c4": "KvK After-Action Report — Alliance Hegemony output and Top 10 Vanguard Warriors",
                    "c5": "Kingdom Analysis (Area Charts) — Chronological Power trajectory visualization",
                    "c6": "All Kingdom Stats (Bar Charts) — Multi-KD comparative Power and KP metrics",
                    "c7": "My Alliance Hub — Dynamic roster filtered by Alliance Tag via AWS query",
                    "c8": "Activity Tracker — Chronological delta comparison (NEW / MISSING / GROWTH)",
                    "c9": "Player Hunter — Cross-Kingdom search via DynamoDB GOV_PROFILE index",
                    "c10":"Mail Generator — KvK Push, Rally, and General message templates",
                    "c11":"Calculators — RSS estimation and Speedup math tools",
                    "c12":"Admin Panel — AWS Cloud Control, Tenant Management, Upload Triggers",
                    "c13":"Replaced monolithic 4,716-line index.html with modular Next.js pages",
                    "c14":"Replaced 4,711-line render-blocking style.css with Tailwind CSS",
                    "c15":"Eliminated 3× exposed credential vulnerabilities from public stages",
                    "c16":"Migrated from self-hosted MySQL to serverless AWS DynamoDB",
                    "c17":"All secrets now strictly server-side via .env.local — never bundled to client",
                    "c18":"Role-based access control on all leader routes (isLeader + Admin gates)"
                },
                "1_5_x": {
                    "label": "Final V1 Patches",
                    "date": "Late 2025",
                    "c1": "AI/Gemini Vision OCR engine for Discord RSS screenshot scanning",
                    "c2": "DKP tracking Discord bot commands (/dkp, /stats, /forge)",
                    "c3": "Alliance tag normalization in CSV ingestion pipeline"
                },
                "1_0_0": {
                    "label": "Unity V1 Launch",
                    "date": "2025",
                    "c1": "Initial Discord bot with /bind, /stats, /roster slash commands",
                    "c2": "Express.js API server with Discord OAuth",
                    "c3": "MySQL database for DKP rosters and governor data",
                    "c4": "Single-page HTML dashboard (index.html 4,716 lines)"
                }
            }
        }
    },
    "zh": {
        "DKP": {
            "title": "DKP 结算",
            "subtitle": "KVK 后的击杀积分统计",
            "no_lethality": "未检测到活跃数据",
            "no_lethality_desc": "无法计算模型。请检查服务器上的最新时间线。",
            "top_vanguard": "最高王国先锋",
            "tier_output": "梯队 {tier} 输出",
            "calculated_dkp": "计算出的 DKP 贡献值",
            "official_commendations": "官方KVK表彰记录",
            "nodes_indexed": "已索引 {count} 玩家",
            "col_rank": "排名",
            "col_grade": "表现评级",
            "col_name": "玩家名",
            "col_dkp": "DKP 总分",
            "col_deads": "阵亡数量",
            "col_kp": "击杀积分增量",
            "dkp_suffix": "(+{val} DKP)"
        },
        "Upload": {
            "title": "数据导入中心",
            "subtitle": "选择一条导入管道，将您的王国情报与 AWS 云端安全同步",
            "raw_spreadsheets": "本地表格",
            "raw_desc": "上传包含数千名玩家数据的 Excel / CSV 扫描件。",
            "cloud_db": "云数据库",
            "cloud_desc": "与 AWS 中央数据库建立直接连接并同步跨王国的最新数据。",
            "ai_scanner": "AI 视觉追踪",
            "ai_desc": "利用 Gemini 机器视觉 AI 模型快速提取玩家档案面板的数据。",
            "in_dev": "开发中"
        },
        "PreKVK": {
            "title": "KVK 前排行榜",
            "subtitle": "全球前300对比",
            "target_scope": "对比范围:",
            "global_scope": "全球所有服务器",
            "enter_kd": "输入王国ID (例如：3065)",
            "target_count": "查询目标: {count} 个王国",
            "col_rank": "排名",
            "col_kingdom": "王国",
            "col_power": "前300名总战力",
            "col_kp": "总击杀分",
            "col_prank": "战力排名",
            "col_kprank": "击杀排名"
        },
        "GlobalAnalysis": {
            "title": "全部服务器分析",
            "subtitle": "跨服宏观数据",
            "camp_builder": "分组器",
            "delta_analytics": "增量分析",
            "all_kd_analysis": "全服数据分析",
            "comprehensive_deltas": "对比战力和击杀积分的提升",
            "filter_kd": "筛选王国",
            "add": "添加",
            "start_scan": "起始扫描:",
            "end_scan": "结束扫描:",
            "col_kd": "王国",
            "col_start_p": "起始总战力",
            "col_end_p": "结束总战力",
            "col_power_d": "战力增减量",
            "col_kp_gained": "击杀增长",
            "col_deads": "阵亡",
            "insufficient": "扫描次数不足，无法计算增缩量"
        },
        "Vault": {
            "title": "王国银行储蓄所",
            "subtitle": "KVK前资源储备监控",
            "kingdom_view": "王国视图",
            "sync_aws": "同步 AWS",
            "override": "机密资产提交",
            "main_acc": "主账号",
            "drag_drop": "拖拽截图上传",
            "drag_desc": "Gemini AI 将为您计算您的农粮木石金币总量，并上传到数据库。",
            "locate_file": "选择文件"
        }
    },
    // Adding es (Spanish fallback) so no crashing
    "es": {
        "DKP": {
            "title": "Resultados DKP",
            "subtitle": "Puntos de Muerte de Dragón (Agregación Post-KvK)",
            "no_lethality": "No se Identificó Letalidad",
            "no_lethality_desc": "No se pueden calcular modelos algorítmicos. Comprueba la lógica de mapeo cronológico sobre la última línea de tiempo del servidor.",
            "top_vanguard": "Vanguardia Innegable del Reino",
            "tier_output": "Rendimiento Nivel {tier}",
            "calculated_dkp": "Contribución DKP Calculada",
            "official_commendations": "Menciones Oficiales KvK",
            "nodes_indexed": "{count} Nodos Indexados",
            "col_rank": "Rango",
            "col_grade": "Grado Rendimiento",
            "col_name": "Nombre de Gobernador",
            "col_dkp": "Total DKP",
            "col_deads": "Caídas (Muertes)",
            "col_kp": "Deltas de Kills",
            "dkp_suffix": "(+{val} DKP)"
         },
         "Upload": {
            "title": "Centro de Ingestión de Datos",
            "subtitle": "Seleccione una tubería de ingestión...",
            "raw_spreadsheets": "Hojas de Cálculo Extensas",
            "raw_desc": "Sube documentos masivos Excel o CSV...",
            "cloud_db": "Base de Datos en la Nube",
            "cloud_desc": "Sincroniza directamente con AWS...",
            "ai_scanner": "Escáner AI",
            "ai_desc": "Extrae perfiles de jugador usando Gemini AI...",
            "in_dev": "EN DESARROLLO"
         },
         "PreKVK": {
            "title": "CLASIFICACIONES PRE-KVK",
            "subtitle": "COMPARACIÓN GLOBAL TOP 300",
            "target_scope": "ALCANCE OBJETIVO:",
            "global_scope": "Alcance Global",
            "enter_kd": "Ingresar KD #",
            "target_count": "ALCANCE OBJETIVO: {count} REINOS",
            "col_rank": "RANGO",
            "col_kingdom": "REINO",
            "col_power": "PODER TOP 300",
            "col_kp": "KP TOTAL",
            "col_prank": "RANGO DE PODER",
            "col_kprank": "RANGO KP"
         },
         "GlobalAnalysis": {
            "title": "ANÁLISIS GLOBAL",
            "subtitle": "DIAGNÓSTICOS MACRO CRUZADOS",
            "camp_builder": "CONSTRUCTOR CAMPO",
            "delta_analytics": "ANALÍTICAS DELTA",
            "all_kd_analysis": "ANÁLISIS DE REINO",
            "comprehensive_deltas": "COMPRENSIVO DELTA PODER",
            "filter_kd": "FILTRAR KD",
            "add": "Añadir",
            "start_scan": "ESCANEO INICIO:",
            "end_scan": "ESCANEO FIN:",
            "col_kd": "REINO",
            "col_start_p": "PODER TOTAL DE INICIO",
            "col_end_p": "PODER TOTAL FINAL",
            "col_power_d": "PODER Δ",
            "col_kp_gained": "KP GANADOS",
            "col_deads": "TROPAS MUERTAS",
            "insufficient": "ESCANEO INSUFICIENTE PARA CALCULAR"
         },
         "Vault": {
            "title": "BÓVEDA DEL REINO",
            "subtitle": "MATRIZ DE RESERVAS",
            "kingdom_view": "VISTA DE REINO",
            "sync_aws": "SINCRONIZAR AWS",
            "override": "ANULACIÓN DE VERIFICACIÓN",
            "main_acc": "CUENTA PRINCIPAL",
            "drag_drop": "ARRASTRAR Y SOLTAR",
            "drag_desc": "Google Gemini IA leerá tus reservas...",
            "locate_file": "LOCALIZAR ARCHIVO"
         }
    }
};

const dir = path.join(process.cwd(), 'src', 'messages');

locales.forEach(loc => {
    const file = path.join(dir, `${loc}.json`);
    if (fs.existsSync(file)) {
        let json = JSON.parse(fs.readFileSync(file, 'utf8'));
        
        let targetData = data[loc] || data["en"];
        json.DKP = targetData.DKP;
        json.Upload = targetData.Upload;
        json.PreKVK = targetData.PreKVK;
        json.GlobalAnalysis = targetData.GlobalAnalysis;
        json.Vault = targetData.Vault || data["en"].Vault;
        json.Settings = targetData.Settings || data["en"].Settings;
        json.Changelog = targetData.Changelog || data["en"].Changelog;
        
        fs.writeFileSync(file, JSON.stringify(json, null, 2), 'utf8');
        console.log(`Updated stragglers for ${loc}.json`);
    }
});
