"use client";

import { useState } from "react";
import { 
  FileSpreadsheet, 
  Cloud, 
  Camera, 
  Upload, 
  ArrowRight,
  Database,
  Github,
  CheckCircle2
} from "lucide-react";

export default function UploadHub() {
  const [activeTab, setActiveTab] = useState(null);

  // Tab Selection Cards
  if (!activeTab) {
    return (
      <div className="animate-fade-in max-w-5xl mx-auto mt-8">
        <div className="text-center mb-12">
          <h1 className="text-3xl font-bold text-white mb-3">Data Ingestion Hub</h1>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Select an ingestion pipeline to synchronize external Kingdom intelligence with the secure AWS Unity Cloud.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Spreadsheet Option */}
          <button 
            onClick={() => setActiveTab("spreadsheet")}
            className="group relative bg-[#0f1115] border border-[#1e222b] hover:border-emerald-500/50 rounded-2xl p-8 text-left transition-all hover:shadow-[0_0_30px_rgba(16,185,129,0.15)] overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
              <FileSpreadsheet size={100} />
            </div>
            <div className="w-14 h-14 bg-emerald-500/10 rounded-xl flex items-center justify-center mb-6 text-emerald-400 group-hover:scale-110 transition-transform">
              <FileSpreadsheet size={28} />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">Raw Spreadsheets</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              Upload massive Excel or CSV bulk scans generated by RokBoard or other OCR extractors to process thousands of governor records.
            </p>
          </button>

          {/* Cloud Sync Option */}
          <button 
            onClick={() => setActiveTab("cloud")}
            className="group relative bg-[#0f1115] border border-[#1e222b] hover:border-indigo-500/50 rounded-2xl p-8 text-left transition-all hover:shadow-[0_0_30px_rgba(99,102,241,0.15)] overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
              <Cloud size={100} />
            </div>
            <div className="w-14 h-14 bg-indigo-500/10 rounded-xl flex items-center justify-center mb-6 text-indigo-400 group-hover:scale-110 transition-transform">
              <Cloud size={28} />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">Cloud Database</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              Establish a direct, encrypted uplink to the centralized AWS datastore to synchronize cross-kingdom timelines instantly.
            </p>
          </button>

          {/* AI Screenshot Option */}
          <button 
            onClick={() => setActiveTab("scanner")}
            className="group relative bg-[#0f1115] border border-[#1e222b] hover:border-amber-500/50 rounded-2xl p-8 text-left transition-all hover:shadow-[0_0_30px_rgba(245,158,11,0.15)] overflow-hidden opacity-50 cursor-not-allowed"
          >
            <div className="absolute top-4 right-4 bg-amber-500/10 text-amber-500 text-[10px] font-bold px-2 py-1 rounded-full uppercase tracking-wider">
              IN DEVELOPMENT
            </div>
            <div className="w-14 h-14 bg-gray-800 rounded-xl flex items-center justify-center mb-6 text-gray-500 group-hover:scale-110 transition-transform">
              <Camera size={28} />
            </div>
            <h3 className="text-xl font-bold text-gray-400 mb-2">AI Vision Scanner</h3>
            <p className="text-gray-500 text-sm leading-relaxed">
              Extract player stat profiles instantly using edge instances of the Gemini Vision AI model.
            </p>
          </button>
        </div>
      </div>
    );
  }

  // Common Pipeline Layout wrapping the specific UI
  return (
    <div className="max-w-6xl mx-auto mt-4 animate-fade-in relative z-10">
      
      {/* Top action bar */}
      <div className="flex items-center gap-4 mb-8 pb-4 border-b border-[#1e222b]">
        <button 
          onClick={() => setActiveTab(null)}
          className="text-gray-400 hover:text-white flex items-center gap-2 text-sm font-medium transition-colors bg-[#1e222b]/50 px-4 py-2 rounded-lg hover:bg-[#1e222b]"
        >
          <ArrowRight className="rotate-180" size={16} />
          Back to Hub
        </button>
        <div>
          <h2 className="text-xl font-bold text-white capitalize">
            {activeTab === 'spreadsheet' ? 'Excel / CSV Pipeline' : 'Cloud Synchronization Pipeline'}
          </h2>
          <p className="text-gray-500 text-xs mt-1">Provide data for Start, Mid (optional), and End scan intervals.</p>
        </div>
      </div>

      {/* Dual-stage Pipeline Render */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-8 max-w-4xl mx-auto mt-8">
        
        {/* Stage 1: Pre-KvK Start */}
        <DropZone 
          title="Start Scan" 
          description="Pre-KvK baseline metrics"
          icon={activeTab === 'cloud' ? <Database className="text-indigo-400" /> : <Upload className="text-emerald-400" />}
          theme={activeTab === 'cloud' ? 'indigo' : 'emerald'}
          isCloud={activeTab === 'cloud'}
        />

        <div className="text-[#1e222b] hidden md:block"><ArrowRight size={32} /></div>

        {/* Stage 2: Post-KvK End */}
        <DropZone 
          title="End Scan" 
          description="Final DKP measurement"
          icon={activeTab === 'cloud' ? <Database className="text-indigo-400" /> : <Upload className="text-emerald-400" />}
          theme={activeTab === 'cloud' ? 'indigo' : 'emerald'}
          isCloud={activeTab === 'cloud'}
        />

      </div>

    </div>
  );
}

// ---------------------------------------------------------------------------------
// Sub-Component: DropZone Configurator
// ---------------------------------------------------------------------------------
function DropZone({ title, description, icon, theme, optional = false, isCloud = false }) {
  
  const themeColors = {
    emerald: 'border-emerald-500/30 hover:border-emerald-500 bg-emerald-500/5',
    amber: 'border-amber-500/30 hover:border-amber-500 bg-amber-500/5',
    indigo: 'border-indigo-500/30 hover:border-indigo-500 bg-indigo-500/5',
  };

  const textColors = {
    emerald: 'text-emerald-400',
    amber: 'text-amber-400',
    indigo: 'text-indigo-400',
  };

  return (
    <div className="w-full flex-1 bg-[#0f1115] rounded-xl border border-[#1e222b] overflow-hidden flex flex-col h-[320px] shadow-lg">
      
      {/* Header */}
      <div className="p-4 border-b border-[#1e222b] bg-[#0a0c0f] flex justify-between items-center">
        <div>
          <h3 className="text-white font-bold">{title}</h3>
          <p className="text-gray-500 text-[10px] uppercase tracking-wider">{description}</p>
        </div>
        {optional && (
          <span className="text-[10px] font-black text-gray-500 border border-gray-700 px-2 py-0.5 rounded-full uppercase">Optional</span>
        )}
      </div>

      {/* Main Action Area */}
      <div className="flex-1 p-6 flex flex-col items-center justify-center relative">
        {isCloud ? (
          <div className="w-full space-y-4">
            <button className={`w-full flex items-center justify-center gap-3 p-4 rounded-lg border border-dashed transition-all group ${themeColors[theme]}`}>
              <Database className={`${textColors[theme]} group-hover:scale-110 transition-transform`} size={24} />
              <div className="text-left">
                <div className={`font-bold ${textColors[theme]}`}>Sync from AWS</div>
                <div className="text-gray-500 text-xs">Pull direct from CloudDB</div>
              </div>
            </button>
            <div className="flex items-center gap-4 w-full px-4 pt-1">
               <div className="h-[1px] bg-[#1e222b] flex-1"></div>
               <span className="text-gray-600 text-[10px] font-bold">OR</span>
               <div className="h-[1px] bg-[#1e222b] flex-1"></div>
            </div>
            <button className="w-full flex items-center justify-center gap-3 p-3 rounded-lg border border-[#1e222b] hover:border-gray-500 hover:bg-white/5 transition-all text-gray-400 group">
              <Github size={20} className="group-hover:text-white transition-colors" />
              <span className="font-semibold text-sm">Load from Github</span>
            </button>
          </div>
        ) : (
          <div className={`w-full h-full rounded-xl border border-dashed ${themeColors[theme]} flex flex-col flex-1 items-center justify-center cursor-pointer group transition-all`}>
            {icon}
            <span className={`mt-3 font-semibold ${textColors[theme]}`}>Drag & Drop Excel File</span>
            <span className="text-gray-500 text-xs mt-1">.xlsx, .csv sizes up to 20MB</span>
          </div>
        )}
      </div>

      {/* Action Footer */}
      <div className="p-4 border-t border-[#1e222b] bg-gradient-to-t from-[#0a0c0f] to-transparent">
        <button className="w-full py-2.5 rounded-md bg-[#1e222b]/50 text-gray-500 font-bold text-sm cursor-not-allowed flex items-center justify-center gap-2">
           <CheckCircle2 size={16} /> Awaiting Data
        </button>
      </div>

    </div>
  );
}
