"use client";

import { useState, useRef, useEffect } from "react";
import { useSession } from "next-auth/react";
import { 
  FileSpreadsheet, Cloud, Camera, Upload, ArrowRight,
  Database, Github, CheckCircle2, AlertTriangle, Loader2, Sparkles 
} from "lucide-react";
import * as XLSX from "xlsx";

export default function UploadHub() {
  const [activeTab, setActiveTab] = useState(null);

  if (!activeTab) {
    return (
      <div className="animate-fade-in w-full mx-auto mt-8">
        <div className="text-center mb-12">
          <h1 className="text-3xl font-bold text-white mb-3">Data Ingestion Hub</h1>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Select an ingestion pipeline to synchronize external Kingdom intelligence with the secure AWS Unity Cloud.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <button 
            onClick={() => setActiveTab("spreadsheet")}
            className="group relative bg-[#0f1115] border border-[#1e222b] hover:border-cyan-500/50 rounded-2xl p-8 text-left transition-all hover:shadow-[0_0_30px_rgba(6,182,212,0.15)] overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
              <FileSpreadsheet size={100} />
            </div>
            <div className="w-14 h-14 bg-cyan-500/10 rounded-xl flex items-center justify-center mb-6 text-cyan-400 group-hover:scale-110 transition-transform">
              <FileSpreadsheet size={28} />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">Raw Spreadsheets</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              Upload massive Excel or CSV bulk scans generated by RokBoard or other OCR extractors to process thousands of governor records.
            </p>
          </button>

          <button 
            onClick={() => setActiveTab("cloud")}
            className="group relative bg-[#0f1115] border border-[#1e222b] hover:border-indigo-500/50 rounded-2xl p-8 text-left transition-all hover:shadow-[0_0_30px_rgba(99,102,241,0.15)] overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
              <Cloud size={100} />
            </div>
            <div className="w-14 h-14 bg-indigo-500/10 rounded-xl flex items-center justify-center mb-6 text-indigo-400 group-hover:scale-110 transition-transform">
              <Cloud size={28} />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">Cloud Database</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              Establish a direct, encrypted uplink to the centralized AWS datastore to synchronize cross-kingdom timelines instantly.
            </p>
          </button>

          <button 
            disabled
            className="group relative bg-[#0f1115] border border-[#1e222b] rounded-2xl p-8 text-left transition-all opacity-50 cursor-not-allowed"
          >
            <div className="absolute top-4 right-4 bg-amber-500/10 text-amber-500 text-[10px] font-bold px-2 py-1 rounded-full uppercase tracking-wider">
              IN DEVELOPMENT
            </div>
            <div className="w-14 h-14 bg-gray-800 rounded-xl flex items-center justify-center mb-6 text-gray-500">
              <Camera size={28} />
            </div>
            <h3 className="text-xl font-bold text-gray-400 mb-2">AI Vision Scanner</h3>
            <p className="text-gray-500 text-sm leading-relaxed">
              Extract player stat profiles instantly using edge instances of the Gemini Vision AI model.
            </p>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full mx-auto mt-4 animate-fade-in relative z-10 pb-12">
      <div className="flex items-center gap-4 mb-8 pb-4 border-b border-[#1e222b]">
        <button 
          onClick={() => setActiveTab(null)}
          className="text-gray-400 hover:text-white flex items-center gap-2 text-sm font-medium transition-colors bg-[#1e222b]/50 px-4 py-2 rounded-lg hover:bg-[#1e222b]"
        >
          <ArrowRight className="rotate-180" size={16} />
          Back to Hub
        </button>
        <div>
          <h2 className="text-xl font-bold text-white capitalize">
            {activeTab === 'spreadsheet' ? 'Excel / CSV Pipeline' : 'Cloud Synchronization Pipeline'}
          </h2>
          <p className="text-gray-500 text-xs mt-1">Provide data for Start, Mid (optional), and End scan intervals.</p>
        </div>
      </div>

      {activeTab === 'spreadsheet' ? (
        <>
          <div className="flex items-center justify-center max-w-2xl mx-auto w-full">
            <DropZone 
              title="Data Injection Node" 
              description="Upload AWS-ready scan payload"
              icon={<Upload className="text-cyan-400" size={32} />}
              theme="cyan"
            />
          </div>
        </>
      ) : (
        <CloudExtractor />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------------
// Sub-Component: Cloud Database Extractor
// ---------------------------------------------------------------------------------
function CloudExtractor() {
  const { data: session } = useSession();
  const [targetKd, setTargetKd] = useState("3155");
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncStatus, setSyncStatus] = useState("idle");
  const [syncResult, setSyncResult] = useState(null);

  useEffect(() => {
    let activeKd = targetKd;
    if (typeof window !== 'undefined') {
        const storedKd = localStorage.getItem('unty_active_kd');
        if (storedKd) {
            activeKd = storedKd;
            setTargetKd(storedKd);
        } else if (session?.user?.tenant?.kingdomId) {
            activeKd = session.user.tenant.kingdomId;
            setTargetKd(activeKd);
        }
    }
  }, [session]);

  const handleSync = async () => {
    setIsSyncing(true);
    setSyncStatus("idle");
    try {
      const res = await fetch(`/api/aws/download?kd=${targetKd}`);
      if (!res.ok) throw new Error("Failed to pull from AWS");
      
      const data = await res.json();
      if (!data.roster) throw new Error("Empty Payload");

      // Generate CSV from JSON Array
      const worksheet = XLSX.utils.json_to_sheet(data.roster);
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, `KD_${targetKd}_Live`);
      
      // Trigger browser download
      XLSX.writeFile(workbook, `Unity_Live_Sync_KD${targetKd}_${new Date().toISOString().split('T')[0]}.xlsx`);

      setDownloadedRows(data.roster.length);
      setSyncStatus("success");
    } catch (e) {
      console.error(e);
      setSyncStatus("error");
    } finally {
      setIsSyncing(false);
    }
  };

  return (
    <div className="bg-[#13161c] border border-[#1e222b] rounded-xl p-8 shadow-xl max-w-3xl mx-auto relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-[100px] pointer-events-none translate-x-1/2 -translate-y-1/2"></div>
        
        <div className="flex flex-col md:flex-row items-center gap-6 relative z-10 mb-8">
            <div className="bg-[#1e222b] p-4 rounded-xl border border-[#2d323e]">
                <Database className="text-indigo-400" size={36} />
            </div>
            <div className="flex-1">
                <h3 className="text-white font-bold text-xl uppercase tracking-widest">DynamoDB Extraction</h3>
                <p className="text-gray-400 text-sm mt-1">
                    Retrieve the live state of the Unity server directly to your local machine as a structured `.xlsx` payload.
                </p>
            </div>
        </div>

        <div className="bg-[#0a0c0f] border border-[#1e222b] rounded-lg p-5 mb-8 flex items-center justify-between">
           <div className="flex flex-col gap-1">
               <label className="text-gray-500 text-[10px] uppercase font-bold tracking-widest">Target Node</label>
               <select 
                 value={targetKd}
                 onChange={(e) => {
                     setTargetKd(e.target.value);
                     setSyncStatus("idle");
                 }}
                 className="bg-transparent text-indigo-400 font-mono font-bold outline-none cursor-pointer"
               >
                 {session?.user?.tenant?.allowedKingdoms?.map(kd => (
                    <option key={kd} value={kd} className="bg-[#0f1115]">Kingdom {kd}</option>
                 ))}
                 {!session?.user?.tenant?.allowedKingdoms?.includes(targetKd) && targetKd && (
                    <option value={targetKd} className="bg-[#0f1115]">Kingdom {targetKd}</option>
                 )}
               </select>
           </div>
           
           <div className="text-right">
               <div className="text-gray-500 text-[10px] uppercase font-bold tracking-widest mb-1">Status</div>
               {isSyncing ? (
                   <div className="text-yellow-500 font-mono font-bold text-sm flex items-center gap-2">
                       <Loader2 size={14} className="animate-spin" /> DOWNLOADING
                   </div>
               ) : syncStatus === 'success' ? (
                   <div className="text-green-500 font-mono font-bold text-sm">SEALED</div>
               ) : syncStatus === 'error' ? (
                   <div className="text-rose-500 font-mono font-bold text-sm">FAILED</div>
               ) : (
                   <div className="text-gray-400 font-mono font-bold text-sm">IDLE / SECURE</div>
               )}
           </div>
        </div>

        <button 
           onClick={handleSync}
           disabled={isSyncing}
           className="w-full py-4 rounded-lg font-bold text-white bg-indigo-600 hover:bg-indigo-500 transition-colors shadow-[0_0_20px_rgba(79,70,229,0.3)] hover:shadow-[0_0_30px_rgba(79,70,229,0.5)] flex justify-center items-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed"
        >
           {isSyncing ? (
               <><Loader2 className="animate-spin" size={20} /> Retrieving Payload...</>
           ) : syncStatus === 'success' ? (
               <><CheckCircle2 size={20} /> Sync Complete ({downloadedRows} Rows)</>
           ) : (
               <><Cloud size={20} /> Initialize Local Download</>
           )}
        </button>
    </div>
  );
}

// ---------------------------------------------------------------------------------
// Sub-Component: DropZone Configurator
// ---------------------------------------------------------------------------------
function DropZone({ title, description, icon, theme, optional = false }) {
  const [isUploading, setIsUploading] = useState(false);
  const [uploadStatus, setUploadStatus] = useState("idle"); // idle, success, error
  const [errorMessage, setErrorMessage] = useState("");
  const [rowCount, setRowCount] = useState(0);
  const fileInputRef = useRef(null);
  
  const themeColors = {
    cyan: 'border-cyan-500/30 hover:border-cyan-500 bg-cyan-500/5',
  };
  const textColors = {
    cyan: 'text-cyan-400',
  };

  const handleDragOver = (e) => {
    e.preventDefault();
  };

  const processFile = (file) => {
    if (!file) return;

    // Heroscrolls Denial Filter 1: Filename Signature
    const lowerName = file.name.toLowerCase();
    if (lowerName.startsWith('kvk_report') || lowerName.startsWith('pre_kvk')) {
      alert("File Rejected: Heroscrolls/Third-Party reports are unsupported. Please upload a pure raw data scan.");
      return;
    }

    setIsUploading(true);
    setUploadStatus("idle");

    const reader = new FileReader();
    reader.onload = async (event) => {
      try {
        const data = new Uint8Array(event.target.result);
        const workbook = XLSX.read(data, { type: 'array' });

        // Heroscrolls Denial Filter 2: Proprietary Tab Signatures
        const heroscrollsTabs = ['deltas', 'start', 'end', 'excluded governors', 'camp totals', 'earth', 'fire', 'water', 'wind'];
        const isHeroscrolls = workbook.SheetNames.some(name => heroscrollsTabs.includes(name.toLowerCase()));
        if (isHeroscrolls) {
          alert("File Rejected: Detected Heroscrolls internal sheet structures (Deltas, Start, End). Please discard this format and upload the raw tracking scan.");
          return;
        }
        
        // Extract DTG from Summary F2 if it exists
        let extractedDtg = null;
        if (workbook.Sheets['Summary']) {
           const summarySheet = workbook.Sheets['Summary'];
           if (summarySheet['F2']) {
               extractedDtg = summarySheet['F2'].w || summarySheet['F2'].v;
           }
        }

        let totalRows = 0;
        let successCount = 0;

        // Discover the overall "Primary Kingdom" for this workbook by finding the first tab possessing a \d{3,} block or relying on the literal filename.
        const primaryKdMatch = workbook.SheetNames.find(s => s.match(/\d{3,}/))?.match(/\d{3,}/);
        const fallbackKdMatch = file.name.match(/\d{3,}/);
        const primaryKd = primaryKdMatch ? primaryKdMatch[0] : (fallbackKdMatch ? fallbackKdMatch[0] : null);

        for (const sheetName of workbook.SheetNames) {
            // EXCLUDE EXTRANEOUS TABS (HeroScrolls / RokBoard Metadata)
            const lowerName = sheetName.toLowerCase();
            if (lowerName.includes('summary') || lowerName.includes('top') || lowerName.includes('rolled up')) {
                continue;
            }

            const worksheet = workbook.Sheets[sheetName];
            
            // Extract >= 3 digit KD from tab string (e.g "KD 1302" -> "1302")
            const extractedKdMatch = sheetName.match(/\d{3,}/);
            const dynamicKd = extractedKdMatch ? extractedKdMatch[0] : primaryKd;
            
            if (!dynamicKd) {
                 console.warn(`[Pipeline] Skiping unmarked auxiliary sheet: ${sheetName}. No Primary Kingdom identifier could be inferred.`);
                 continue; // A valid route is totally mandatory to fire the DB Hooks
            }

            const jsonPayloadRaw = XLSX.utils.sheet_to_json(worksheet, { defval: 0 }); 
            if (!jsonPayloadRaw || jsonPayloadRaw.length === 0) continue;

            // SANITIZER ENGINE: Forcibly strip trailing whitespaces from third-party CSV headers (e.g 'Alliance ')
            const jsonPayload = jsonPayloadRaw.map(row => {
               const sanitizedRow = {};
               for (const key in row) {
                   sanitizedRow[key.trim()] = row[key];
               }
               return sanitizedRow;
            });

            // Optional: Filter out empty rows where ID is missing
            const validPayload = jsonPayload.filter(p => p.id || p.Id || p.ID || p['Governor ID'] || p['Character ID'] || p.CharacterID || p.name || p.NAME || p["Governor Name"] || p.Username || p.username);
            if (validPayload.length === 0) continue;

            setUploadStatus("idle");
            
            // Transmit via Next.js Server APi
            const res = await fetch('/api/aws/upload', {
              method: 'POST',
               headers: { 'Content-Type': 'application/json' },
               body: JSON.stringify({
                 kingdomId: dynamicKd, 
                 rosterArray: validPayload,
                 scanDateOverride: extractedDtg,
                 sourceFile: file.name
               })
            });

            const resData = await res.json();
            if (res.ok) {
                successCount++;
                totalRows += validPayload.length;
            } else {
                console.error(`Tab ${sheetName} failed:`, resData);
            }
        }
        
        if (successCount === 0) throw new Error("This isn't allowed. Please talk to the administrator.");
        
        setRowCount(totalRows);
        setUploadStatus("success");
      } catch (err) {
        console.error("Pipeline Drop Error:", err);
        setErrorMessage(err.message || "Transmission Defaulted");
        setUploadStatus("error");
      } finally {
        setIsUploading(false);
      }
    };
    reader.readAsArrayBuffer(file);
  };

  return (
    <div className={`w-full flex-1 bg-[#0f1115] rounded-xl border transition-all duration-500 overflow-hidden flex flex-col min-h-[320px] shadow-lg ${uploadStatus === 'success' ? 'border-cyan-500 shadow-[0_0_30px_rgba(6,182,212,0.2)]' : 'border-[#1e222b]'}`}>
      
      <div className="p-4 border-b border-[#1e222b] bg-[#0a0c0f] flex justify-between items-center">
        <div>
          <h3 className="text-white font-bold">{title}</h3>
          <p className="text-gray-500 text-[10px] uppercase tracking-wider">{description}</p>
        </div>
        {optional && <span className="text-[10px] font-black text-gray-500 border border-gray-700 px-2 py-0.5 rounded-full uppercase">Optional</span>}
      </div>

      <div 
        onClick={() => !isUploading && fileInputRef.current?.click()}
        onDragOver={handleDragOver}
        onDrop={(e) => {
          e.preventDefault();
          if (!isUploading) {
            processFile(e.dataTransfer.files?.[0]);
          }
        }}
        className="flex-1 p-6 flex flex-col items-center justify-center relative cursor-pointer group"
      >
        <input 
          type="file" 
          ref={fileInputRef} 
          className="hidden" 
          accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
          onChange={(e) => processFile(e.target.files?.[0])}
        />

        {isUploading ? (
          <div className="flex flex-col items-center justify-center text-indigo-400 p-8">
            <Loader2 className="animate-spin mb-4" size={40} />
            <span className="font-bold text-sm tracking-wider uppercase animate-pulse">Igniting DynamoDB Pipeline...</span>
            <span className="text-xs text-gray-500 mt-2 font-mono">Transmitting JSON Blocks</span>
          </div>
        ) : uploadStatus === "success" ? (
          <div className="w-full h-full rounded-xl border border-cyan-500 bg-cyan-500/10 flex flex-col items-center justify-center text-cyan-400 group-hover:bg-cyan-500/20 transition-colors">
             <CheckCircle2 size={48} className="mb-3" />
             <div className="font-black text-xl">SUCCESS</div>
             <div className="text-xs font-bold uppercase mt-1 tracking-wider text-cyan-600 bg-cyan-950 px-3 py-1 rounded">AWS Pipeline Sealed</div>
             <div className="text-[10px] text-cyan-400 mt-4 font-mono font-bold">[{rowCount} Data Nodes Synchronized]</div>
             <div className="text-[11px] text-white mt-6 font-bold tracking-[0.2em] uppercase opacity-70 group-hover:opacity-100 transition-opacity">Click or Drop Next File</div>
          </div>
        ) : uploadStatus === "error" ? (
          <div className="w-full h-full rounded-xl border border-rose-500 border-dashed bg-rose-500/5 flex flex-col items-center justify-center text-rose-500 cursor-pointer hover:bg-rose-500/10 transition-colors px-6 text-center">
             <AlertTriangle size={36} className="mb-2" />
             <span className="font-bold text-sm">{errorMessage || 'Transmission Failure'}</span>
             <span className="text-[10px] uppercase font-bold tracking-widest mt-2 text-rose-400">Click to Retry Ignition</span>
          </div>
        ) : (
          <div className={`w-full h-full rounded-xl border border-dashed ${themeColors[theme]} flex flex-col flex-1 items-center justify-center cursor-pointer group transition-all`}>
            {icon}
            <span className={`mt-3 font-semibold ${textColors[theme]}`}>Select Local File</span>
            <span className="text-gray-500 text-xs mt-1">Accepts raw .xlsx or CSV</span>
          </div>
        )}
      </div>

      <div className="p-4 border-t border-[#1e222b] bg-gradient-to-t from-[#0a0c0f] to-transparent">
        <button className={`w-full py-2.5 rounded-md font-bold text-sm flex items-center justify-center gap-2 transition-all ${
          uploadStatus === 'success' ? 'bg-cyan-500 text-white shadow-[0_0_15px_rgba(6,182,212,0.3)]' : 'bg-[#1e222b]/50 text-gray-500 cursor-not-allowed'
        }`}>
           {uploadStatus === 'success' ? 'Ignition Sequence Complete' : 'Awaiting Data Payload'}
        </button>
      </div>

    </div>
  );
}
